### PR TITLE
Add website remote integration

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds settings and functionality to update the user's position on the interactive map displayed on the Tarkov.dev website.

(ignore the branch name)

### CODE REVIEW

**Review by thaddeus — APPROVED** [review]
This is awesome! 👍

**Comment by Evenkarke** [comment]
How to install?

**Comment by Razzmatazzz** [comment]
@Evenkarke We have to merge this PR into the main branch and create a new release.

**Comment by Evenkarke** [comment]
> @Evenkarke We have to merge this PR into the main branch and create a new release.

Hey, im new to github, does this mean i cannot install it now?

**Comment by Razzmatazzz** [comment]
You could clone this branch of the repository to your computer, open it in visual studio, and then compile it for yourself.

If you don't want to do that, you can just wait for the next release.

**Pull request merged**
